[package]
name = "ga-sim"
version = "0.1.0"
edition = "2024"

[profile.release]
lto = "thin"
codegen-units = 1
debug = true

[dependencies]
wisc = { git = "https://github.com/amirreiter/wisc.git" }

# crabtime is broken on nightly, so we use a fork to fix it
# see https://github.com/wdanilo/crabtime/pull/41
crabtime = { git = "https://github.com/Nekomaru-PKU/crabtime.git" }
csv = "1.4.0"
glam = "0.32"
itertools = "0.14.0"
obvhs = { git = "https://github.com/amirreiter/obvhs.git" }
paste = "1.0.15"
tobj = "4.0.3"
rayon = "1.11.0"
thread_local = "1.1.9"
serde_json = "1.0"
hound = "3.5.1"
